version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgrestesttwo
    volumes:
      - postgrestesttwo:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=postgres20
         - POSTGRES_USER=postgres
         - POSTGRES_DB=springtestdb
    restart: unless-stopped

  springbootapp:
    image: springio/demo:latest
    expose:
      - 8761
    ports:
      - 8761:8761
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: container
volumes:
  postgrestesttwo: